name: AWS Connection Test

on:
  workflow_dispatch:

jobs:
  verify-aws:
    name: 🔍 Verify AWS Access and S3 Connectivity
    runs-on: ubuntu-24.04

    steps:
      - name: 🧩 Checkout repository
        uses: actions/checkout@v4

      - name: ⚙️ Install AWS CLI
        run: |
          if ! command -v aws &>/dev/null; then
            curl -s "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
            unzip -qq awscliv2.zip
            sudo ./aws/install
          fi

      - name: ☁️ Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_DEFAULT_REGION }}

      - name: 🔑 Verify STS identity and S3 access
        env:
          S3_BUCKET: ${{ secrets.S3_BUCKET }}
        run: |
          set -e
          echo "🔍 Testing AWS identity..."
          aws sts get-caller-identity
          echo "✅ STS identity confirmed."

          echo "🌍 Listing S3 bucket..."
          aws s3 ls s3://$S3_BUCKET
          echo "✅ S3 bucket access successful."

          echo "📤 Uploading test file..."
          echo "Hello from Solvionyx workflow" > test.txt
          aws s3 cp test.txt s3://$S3_BUCKET/test/test.txt --acl public-read
          echo "✅ Test upload successful."
          echo "🌐 Access via: https://$S3_BUCKET.s3.${{ secrets.AWS_DEFAULT_REGION }}.amazonaws.com/test/test.txt"
