wallpaper = Image("background.jpg");
logo = Image("logo.png");

scr_w = Window.GetWidth();
scr_h = Window.GetHeight();

scale = scr_w / wallpaper.GetWidth();
wall_h = wallpaper.GetHeight() * scale;

wallpaper.Draw(0, (scr_h - wall_h) / 2, scale, scale);

logo_scale = 0.23;
lw = scr_w * logo_scale;
lh = logo.GetHeight() * (lw / logo.GetWidth());

lx = (scr_w - lw) / 2;
ly = (scr_h - lh) / 2;

logo.Draw(lx, ly, lw/logo.GetWidth(), lh/logo.GetHeight());

