name: Auto Changelog
on:
  push:
    branches: ["main"]
jobs:
  changelog:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - uses: stefanzweifel/changelog-action@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
