name: Auto Version Tag
on: { workflow_dispatch: {} }
jobs:
  tag:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - run: DATE=$(date +'%Y.%m.%d') && git tag "v$DATE" && git push origin --tags
