name: Sync Solvionyx OS Changelog to Website

on:
  workflow_run:
    workflows:
      - "Auto Update Changelog (Aurora Series)"
    types:
      - completed

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: 📦 Checkout Repository
        uses: actions/checkout@v4

      - name: ⚙️ Prepare Aurora Web Page
        run: |
          mkdir -p web_build
          {
            echo "<!DOCTYPE html><html lang='en'><head>"
            echo "<meta charset='UTF-8'>"
            echo "<meta name='viewport' content='width=device-width, initial-scale=1.0'>"
            echo "<title>Solvionyx OS — Aurora Series</title>"
            echo "<link href='https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css' rel='stylesheet'>"
            echo "<style>
              body {
                background: radial-gradient(circle at top left, #0b0c10, #090909);
                color: #e0e0e0;
                font-family: 'Inter', sans-serif;
              }
              h1, h2, h3 { color: #4fe0b0; }
              .card {
                background: #161616;
                border: 1px solid #2a2a2a;
                border-radius: 1rem;
                padding: 1rem 1.25rem;
                margin-bottom: 1rem;
                box-shadow: 0 0 15px rgba(79,224,176,0.1);
                transition: transform 0.2s ease;
              }
              .card:hover {
                transform: translateY(-3px);
                box-shadow: 0 0 20px rgba(79,224,176,0.3);
              }
              a.btn-download {
                background: linear-gradient(90deg,#4fe0b0,#36c5d5);
                border: none;
                color: #000;
                font-weight: 600;
                border-radius: 50px;
                padding: 8px 16px;
                text-decoration: none;
              }
              a.btn-download:hover {
                filter: brightness(1.15);
              }
              footer {
                margin-top: 3rem;
                padding: 1rem;
                font-size: 0.9rem;
                color: #aaa;
              }
              pre {
                background: #0e0e0e;
                border-radius: 0.5rem;
                padding: 1rem;
                overflow-x: auto;
                white-space: pre-wrap;
              }
            </style>"
            echo "</head><body class='container py-4'>"
            echo "<h1 class='mb-4 text-center fw-bold'>Solvionyx OS — Aurora Series</h1>"
            echo "<p class='text-center'>Official builds of the Solvionyx Aurora OS, featuring GNOME, XFCE, and KDE editions.<br>Auto-generated directly from GitHub Actions.</p>"
            echo "<hr><div class='mt-4'>"

            # Convert CHANGELOG.md to styled HTML cards
            awk '
              /^## / { if (NR>1) print "</div>"; print "<h2 class=\"mt-5\">" substr($0,4) "</h2><div class=\"mt-3\">"; next }
              /^### / { ver=substr($0,5); print "<div class=\"card\"><h3>" ver "</h3>"; next }
              /^- ✅/ { gsub(/^- ✅ /,"<p><strong>Status:</strong> "); print $0 "</p>"; next }
              /^- ⏱️/ { gsub(/^- ⏱️ /,"<p><strong>Build Time:</strong> "); print $0 "</p>"; next }
              /^- 💾/ { gsub(/^- 💾 /,"<p><strong>ISO Size:</strong> "); print $0 "</p>"; next }
              /^- 🔐/ { gsub(/^- 🔐 /,"<p><strong>Checksum:</strong> "); print $0 "</p>"; next }
              /^$/ { next }
              { print "<p>" $0 "</p>" }
            ' CHANGELOG.md >> web_build/index.html

            # Add download button (links to GitHub releases)
            echo "<div class='text-end mt-2 mb-1'>"
            echo "<a class='btn-download' href='https://github.com/solviony/Solvionyx-OS/releases/latest' target='_blank'>⬇ Download Latest ISO</a>"
            echo "</div>"

            echo "</div><footer class='text-center'>
            © 2025 Solviony Labs by Solviony Inc. — Aurora Series. All Rights Reserved.
            </footer></body></html>"
          } > web_build/index.html

      - name: 🌐 Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GH_TOKEN }}
          publish_dir: web_build
          publish_branch: gh-pages
          cname: solviony.com/page/os
